# Generated by Django 6.0.4 on 2026-04-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='e.g., fas fa-network-wired', max_length=100)),
                ('icon_color_class', models.CharField(help_text='e.g., text-accent', max_length=100)),
                ('border_color_code', models.CharField(blank=True, help_text='e.g., #6366f1 or empty for default accent', max_length=50, null=True)),
                ('bg_color_class', models.CharField(help_text='e.g., bg-blue-50 dark:bg-blue-950/50', max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('typed_text_strings', models.CharField(help_text='Comma-separated strings for typed text effect', max_length=255)),
                ('description', models.TextField()),
                ('cv_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('status_label', models.CharField(default='Available for opportunities', max_length=50)),
                ('open_to_work', models.BooleanField(default=True)),
                ('experience_summary', models.CharField(max_length=100)),
                ('education_summary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_cat', models.CharField(help_text='e.g., routing', max_length=50, unique=True)),
                ('is_active_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('color_class', models.CharField(help_text='e.g., text-accent', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='e.g., fas fa-network-wired', max_length=100)),
                ('icon_color_class', models.CharField(help_text='e.g., text-accent/60', max_length=100)),
                ('gradient_from', models.CharField(help_text='e.g., from-blue-50 dark:from-blue-950/40', max_length=100)),
                ('gradient_to', models.CharField(help_text='e.g., to-indigo-50 dark:to-indigo-950/40', max_length=100)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, help_text='e.g., 2024 - 2025 · 6 Months', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, to='core.projecttag')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='e.g., fas fa-microchip', max_length=100)),
                ('icon_color_class', models.CharField(help_text='e.g., text-accent', max_length=100)),
                ('level', models.CharField(blank=True, help_text='e.g., Advanced', max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
